server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-microservice
          uri: lb://user-microservice
          predicates:
            - Path=/user/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: car-microservice
          uri: lb://car-microservice
          predicates:
            - Path=/car/**
        - id: bike-microservice
          uri: lb://bike-microservice
          predicates:
            - Path=/bike/**
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:100/realms/tutorial-realm/protocol/openid-connect/auth
            userinfo-uri: http://localhost:100/realms/tutorial-realm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            token-uri: http://localhost:100/realms/tutorial-realm/protocol/openid-connect/token
        registration:
          client-name:
            provider: keycloak
            client-id: tutorial-client
            client-secret: WpLXgID2HJuchPYnmnOuqnW63Z2kBssS
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/tutorial-client"