server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
<<<<<<< HEAD
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-microservice
          uri: lb://user-microservice
          predicates:
            - Path=/user/**
        - id: car-microservice
          uri: lb://car-microservice
          predicates:
            - Path=/car/**
        - id: bike-microservice
          uri: lb://bike-microservice
          predicates:
            -Path=/bike/**
=======
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
                - id: user-service
                  uri: lb://user-service
                  predicates:
                      - Path=/user/**
            routes:
                - id: car-microservice
                  uri: lb://car-microservice
                  predicates:
                      - Path=/car/**
            routes:
                - id: bike-microservice
                  uri: lb://bike-microservice
                  predicates:
                      - Path=/bike/**
>>>>>>> 233cd5c5d2080e1a45e6b2e7919dea159b380d14
